PREFIX = ..
DTX.sty.base = mathhub mikoslides-mh modules-mh omtext-mh problem-mh \
smultiling-mh structview-mh tikzinput-mh
TDSCOLL = mathhub
CTANPREFIX = sty/
PACKAGE = mathhub
DTX = mathhub.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

