PREFIX = ..
DTX.sty.base = problem
DTX.cls.base = 
TDSCOLL = stex# lowercase by CTAN rules
CTANPREFIX = sty/
PACKAGE = problem
DTX = problem.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

