PREFIX = ../..
DTX.sty.base = sref
EXAMPLE.base = idc scr book 
TDS.doc = idcmain.tex scrmain.tex
CTAN = $(TDS.doc)
TDSCOLL = stex
CTANPREFIX = sty/
PACKAGE = sref
DTX = sref.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

