PREFIX = ../..
DTX.sty.base = structview
STY =
DTX.cls.base = 
TDSCOLL = stex
CTANPREFIX = sty/
PACKAGE = structview
DTX = structview.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in


