PREFIX = ..
DTX.sty.base = tikzinput
TDSCOLL = stex# lowercase by CTAN rules
CTANPREFIX = sty/
PACKAGE = tikzinput
DTX = tikzinput.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

