PREFIX = ../..
DTX.sty.base = cmathml
DTX.cls.base = 
TDSCOLL = stex
CTANPREFIX = /sty
PACKAGE = cmathml
TDS.tex =  cmathmlx.sty  cmathmlx.sty.ltxml
CTAN = $(TDS.tex)
include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

