PREFIX = ../..
DTX.sty.base = cmathml
DTX.cls.base = 
TDSCOLL = stex
CTANPREFIX = sty/
PACKAGE = cmathml
DTX = cmathml.dtx
TDS.tex =  cmathmlx.sty
CTAN = $(TDS.tex)
include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

