%%
%% This is file `smglom.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% smglom.dtx  (with options: `cls')
%% 
\NeedsTeXFormat{LaTeX2e}[1999/12/01]
\ProvidesClass{smglom}[2016/04/06 v0.1 Semantic Multilingual Glossary for Math]
\DeclareOption*{\PassOptionsToClass{\CurrentOption}{omdoc}
                           \PassOptionsToPackage{\CurrentOption}{stex}
                           \PassOptionsToPackage{\CurrentOption}{smglom}}
\ProcessOptions
\LoadClass{omdoc}
\RequirePackage{smglom}
\RequirePackage{stex}
\RequirePackage{amstext}
\RequirePackage{amsfonts}
\endinput
%%
%% End of file `smglom.cls'.
