PREFIX = ..
DTX.sty.base =  hwexam
DTX.cls.base = hwexam
TDSCOLL = stex# lowercase by CTAN rules
CTANPREFIX = sty/
PACKAGE = hwexam
DTX = hwexam.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

