PREFIX = ../..
DTX.sty.base =  presentation 
STY = 
DTX.cls.base = 
TDSCOLL = sTeX
CTANPREFIX = sty/
PACKAGE = presentation
DTX = presentation.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

