PREFIX = ..
DTX.sty.base = mikoslides
DTX.cls.base = mikoslides
TDSCOLL = stex
CTANPREFIX = /sty
PACKAGE = mikoslides
TDS.tex = beamerthemeJacobs.sty cc-by-sa.png cc_somerights.png\
	  jacobs-logo.png mikoaffiliation.sty mikoaffiliation.sty.ltxml\
	  shading-l2r.png dangerous-bend.png

CTAN 	= $(TDS.tex)

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

