PREFIX = ..
DTX.sty.base = mikoslides
DTX.cls.base = mikoslides
TDSCOLL = stex# lowercase by CTAN rules
CTANPREFIX = sty/
PACKAGE = mikoslides
DTX = mikoslides.dtx
TDS.tex = beamerthemeJacobs.sty cc-by-sa.png cc_somerights.png\
	  jacobs-logo.png shading-l2r.png dangerous-bend.png

CTAN 	= $(TDS.tex)

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

