PREFIX = ../..
DTX.sty.base =  statements
STY = 
DTX.cls.base = 
TDSCOLL = sTeX
CTANPREFIX = sty/
PACKAGE = statements
DTX = statements.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

echo:
	echo $(BIBINPUTS)
