PREFIX = ../..
DTX.sty.base =  statements
STY = 
DTX.cls.base = 
TDSCOLL = stex
CTANPREFIX = sty/
PACKAGE = statements

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

echo:
	echo $(BIBINPUTS)
