PREFIX = ..
DTX.sty.base =  cmath
STY = 
DTX.cls.base = 
TDSCOLL = stex# lowercase by CTAN rules
CTANPREFIX = sty/
PACKAGE = cmath
DTX = cmath.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

