PREFIX = ../..
DTX.sty.base = omtext
TDSCOLL = stex# lowercase by CTAN rules
CTANPREFIX = sty/
PACKAGE = omtext
DTX = omtext.dtx

include $(PREFIX)/make/Makefile.vars
PDFLATEX = pdflatex -file-line-error
include $(PREFIX)/make/Makefile.in
