PREFIX = ..
DTX.sty.base = smultiling
TDSCOLL = stex# lowercase by CTAN rules
CTANPREFIX = sty/
PACKAGE = smultiling
DTX = smultiling.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

