PREFIX = ..
DTX.sty.base = stex-master
STY =
DTX.cls.base = 
TDSCOLL = stex# lowercase by CTAN rules
CTANPREFIX = sty/
PACKAGE = stex
DTX = stex.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in


