PREFIX = ..
DTX.sty.base = stex-master
STY =
DTX.cls.base = 
TDSCOLL = stex# lowercase by CTAN rules
CTANPREFIX = sty/
PACKAGE = stex-master
DTX = stex-master.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in


