%%
%% This is file `smglom.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% stex.dtx  (with options: `smglom')
%% 
\RequirePackage{expl3,l3keys2e}
\ProvidesExplClass{smglom}{2021/08/01}{1.9}{sTeX1 compatibility}
\LoadClass[border=1px,varwidth]{standalone}
\setlength\textwidth{15cm}
\DeclareOption*{\PassOptionsToPackage{\CurrentOption}{stex}}
\ProcessOptions

\RequirePackage{stex-compatibility}


\endinput
%%
%% End of file `smglom.cls'.
