PREFIX = ../..
DTX.sty.base =  physml
STY = 
DTX.cls.base = 
TDSCOLL = stex
CTANPREFIX = sty/
PACKAGE = physml 
DTX = physml.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

