PREFIX = ../..
DTX.sty.base = metakeys
DTX.cls.base = 
TDSCOLL = stex# lowercase by CTAN rules
CTANPREFIX = sty/
PACKAGE = metakeys
DTX = metakeys.dtx
include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

