PREFIX = ..
DTX.sty.base = pathsuris
STY =
DTX.cls.base = 
TDSCOLL = stex# lowercase by CTAN rules
CTANPREFIX = sty/
PACKAGE = pathsuris
DTX = pathsuris.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in


