PREFIX = ..
DTX.sty.base = stex-metakeys
DTX.cls.base = 
TDSCOLL = stex# lowercase by CTAN rules
CTANPREFIX = sty/
PACKAGE = stex-metakeys
DTX = stex-metakeys.dtx
include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

