PREFIX = ../..
DTX.cls.base = smglom
TDSCOLL = stex# lowercase by CTAN rules
CTANPREFIX = sty/
PACKAGE = smglom
DTX = smglom.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

