%%
%% This is file `smglom.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% smglom.dtx  (with options: `cls')
%% 
\NeedsTeXFormat{LaTeX2e}[1999/12/01]
\ProvidesClass{smglom}[2013/05/27 v0.1 Semantic Multilingual Glossary for Math]
\DeclareOption*{\PassOptionsToClass{\CurrentOption}{omdoc}}
\ProcessOptions
\LoadClass{omdoc}
\RequirePackage{amstext}
\RequirePackage{modules}
\RequirePackage{dcm}
\RequirePackage{statements}
\RequirePackage{sproof}
\RequirePackage{cmath}
\RequirePackage{presentation}
\RequirePackage{amsfonts}
\RequirePackage[english,ngerman]{babel}
\RequirePackage{smglom}
\endinput
%%
%% End of file `smglom.cls'.
