PREFIX = ../..
DTX.sty.base = omdoc
DTX.cls.base = omdoc
TDSCOLL = stex # lowercase by CTAN rules
CTANPREFIX = sty/
PACKAGE = omdoc
DTX = omdoc.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

