PREFIX = ../..
DTX.sty.base = modules
STY =
DTX.cls.base = 
TDSCOLL = stex# lowercase by CTAN rules
CTANPREFIX = sty/
PACKAGE = modules
DTX = modules.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in


