PREFIX = ..
DTX.sty.base = dcm
DTX.cls.base = 
TDSCOLL = stex# lowercase by CTAN rules
CTANPREFIX = sty/
PACKAGE = dcm
DTX = dcm.dtx
include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in
