STC = ../..
PREFIX = ..
DTX.sty.base = dcm
DTX.cls.base = 
TDSCOLL = stex
CTANPREFIX = /sty
PACKAGE = dcm
include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

TARGET = all.tex
BUTFILES = pre.tex
include $(STC)/make/Makefile.vars
include $(STC)/make/Makefile.in
