PREFIX = ../..
DTX.sty.base =  sproof 
STY = 
DTX.cls.base = 
TDSCOLL = sTeX
CTANPREFIX = sty/
PACKAGE = sproof
DTX = sproof.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

