PREFIX = ../..
DTX.sty.base = workaddress
DTX.cls.base = 
TDSCOLL = sTeX
CTANPREFIX = sty/
PACKAGE = workaddress
DTX = workaddress.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

