STEXDIR = ../..
TARGET = all.tex
BUTFILES = pre.tex post.tex
MODSLIBDIR = .
BIBINPUTS = $(PREFIX)/lib/bib:

include $(STEXDIR)/lib/make/Makefile.vars
all: pdf mpdf
include $(STEXDIR)/lib/make/Makefile.in 
