PREFIX = ..
DTX.sty.base = workaddress
DTX.cls.base = 
TDSCOLL = stex# lowercase by CTAN rules
CTANPREFIX = sty/
PACKAGE = workaddress
DTX = workaddress.dtx

include $(PREFIX)/make/Makefile.vars
include $(PREFIX)/make/Makefile.in

